version: '2'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - flippy
    ports:
      - '9002:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../flippy/static/:/usr/share/nginx/html:ro

  flippy:
    image: giftig/flippy:0.1.3-SNAPSHOT
    depends_on:
      - redis
    ports:
      - '9001:8080'
    volumes:
      - ./build:/usr/local/flippy
    command: '--port 8080 --backend-host redis --backend-port 6379'

  redis:
    image: redis
